import { NgModule, APP_INITIALIZER } from '@angular/core';
import { HTTP_INTERCEPTORS } from "@angular/common/http";
import { HashLocationStrategy, LocationStrategy } from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';

import { ToastModule } from 'primeng/toast';

import { AppComponent } from './app.component';
import { NotfoundComponent } from './main/components/notfound/notfound.component';

// import { LoginFormModule } from './main/components/pages/login/login-form/login-form.module';
import { AppRoutingModule } from './app-routing.module';
import { AppLayoutModule } from './layout/components/app.layout.module';

import { ErrorInterceptor } from './main/interceptors/error.interceptor';
import { JwtInterceptor } from './main/interceptors/jwt.interceptor';

import { NgIconsModule } from '@ng-icons/core';
import {
    tablerReceipt2,
    tablerUsers,
    tablerCheck,
    tablerCreditCard,
    tablerCashBanknote,
    tablerBrandCashapp,
    tablerBuildingBank,
    tablerNumber,
    tablerCalendar,
    tablerListDetails,
    tablerUserCancel,
    tablerWriting,
    tablerSquareX,
    tablerLoader,
    tablerSettingsDown,
    tablerPhotoPlus,
    tablerRotate,
    tablerRotateClockwise,
    tablerFlipHorizontal,
    tablerFlipVertical,
    tablerRefresh,
    tablerAspectRatio,
    tablerAspectRatioOff,
    tablerPhotoEdit,
    tablerCertificate,
    tablerBriefcase,
    tablerBuildingEstate,
    tablerBrandTerraform,
    tablerNote,
    tablerFence,
    tablerMapSearch,
    tablerDirections,
    tablerDimensions,
    tablerMap,
    tablerCompass,
    tablerHistory,
    tablerCashOff,
    tablerDoorExit,
    tablerPlus,
    tablerCertificateOff,
    tablerFileTime,
    tablerCar,
    tablerUser,
    tablerFileDescription,
    tablerAt,
    tablerZoomQuestion,
    tablerFileTypePdf,
    tablerPencilCheck,
    tablerMenu2,
    tablerSearch,
    tablerList,
    tablerBuildingFactory2,
    tablerEngine,
    tablerPalette,
    tablerPigMoney,
    tablerCurrencyDollar,
    tablerCoin,
    tablerJacket,
    tablerPackageImport,
    tablerPackage,
    tablerReportSearch,
    tablerTextScan2,
    tablerPaperclip,
    tablerFileDownload,
    tablerDownload,
    tablerLibrary,
    tablerFileUnknown,
    tablerPercentage,
    tablerBrandMailgun,
    tablerMail,
    tablerFileX,
} from '@ng-icons/tabler-icons';

@NgModule({
    declarations: [
      AppComponent, 
    ],
    imports: [
      AppRoutingModule,
      AppLayoutModule,
      NotfoundComponent,
      BrowserModule,

      NgIconsModule.withIcons({
          tablerReceipt2,
          tablerUsers,
          tablerCheck,
          tablerCreditCard,
          tablerCashBanknote,
          tablerBrandCashapp,
          tablerBuildingBank,
          tablerNumber,
          tablerCalendar,
          tablerListDetails,
          tablerUserCancel,
          tablerWriting,
          tablerSquareX,
          tablerLoader,
          tablerSettingsDown,
          tablerPhotoPlus,
          tablerRotate,
          tablerRotateClockwise,
          tablerFlipHorizontal,
          tablerFlipVertical,
          tablerRefresh,
          tablerAspectRatio,
          tablerAspectRatioOff,
          tablerPercentage,
          tablerPhotoEdit,
          tablerCertificate,
          tablerBriefcase,
          tablerBuildingEstate,
          tablerBrandTerraform,
          tablerNote,
          tablerFence,
          tablerMapSearch,
          tablerDirections,
          tablerDimensions,
          tablerMap,
          tablerCompass,
          tablerHistory,
          tablerCashOff,
          tablerDoorExit,
          tablerPlus,
          tablerCertificateOff,
          tablerFileTime,
          tablerCar,
          tablerUser,
          tablerFileDescription,
          tablerAt,
          tablerZoomQuestion,
          tablerFileTypePdf,
          tablerPencilCheck,
          tablerMenu2,
          tablerSearch,
          tablerList,
          tablerBuildingFactory2,
          tablerEngine,
          tablerPalette,
          tablerPigMoney,
          tablerCurrencyDollar,
          tablerCoin,
          tablerJacket,
          tablerPackageImport,
          tablerPackage,
          tablerReportSearch,
          tablerTextScan2,
          tablerPaperclip,
          tablerFileDownload,
          tablerDownload,
          tablerLibrary,
          tablerFileUnknown,
          tablerBrandMailgun,
          tablerMail,
          tablerFileX
      }),
      ToastModule,
    ],
    providers: [
      { provide: LocationStrategy,
        useClass: HashLocationStrategy
      },
      { provide: HTTP_INTERCEPTORS,
        useClass: JwtInterceptor,
        multi: true
      },
      { provide: HTTP_INTERCEPTORS,
        useClass: ErrorInterceptor,
        multi: true
      }
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
